### PR TITLE
Fix macOS bundling issue.

### PR DESCRIPTION
**Pull request by yxwangcs**
Fixed the bundling issues for macOS. The build script also generates a dmg (compressing the app to ~150mb) for better distribution.

I followed the same convention as windows and linux builds, which assumes you have to manually download the web interface to build/dist folder. 

The build is set up on GitHub actions (macos-latest, QT 5.15.2) (https://github.com/yxwangcs/jellyfin-media-player/actions/runs/731108323), you can download `bundle.dmg` and verify it working. I didn't test if this breaks anything on other platforms though.

### CODE REVIEW

**Comment by iwalton3** [comment]
Awesome! I'm going to add that build config too as I don't have a mac.

**Comment by haykkh** [comment]
Thanks for the fix @yxwangcs! Works great on my end

**Comment by iwalton3** [comment]
I see you're looking at the build configuration again and got install-qt-action to actually work on Windows. (It originally wasn't bundling dependencies.)

The Mac OS build doesn't actually work. It is looking for dylibs outside of the bundle directory. I think it might need a static MPV build of some sort.

I was originally only running the builds on the release branch because the CI run probably downloads some 6 GB of packages/dependencies each time it runs which just seemed wasteful.

**Comment by yxwangcs** [comment]
> The Mac OS build doesn't actually work. It is looking for dylibs outside of the bundle directory. I think it might need a static MPV build of some sort.

Yeah I noticed that, too. Strangely `brew install mpv --HEAD` worked in the first place. Does it work now since I see you've fixed the config to compile everything from source?

> I was originally only running the builds on the release branch because the CI run probably downloads some 6 GB of packages/dependencies each time it runs which just seemed wasteful.

Agreed. Too bad GitHub actions doesn't have qt embedded. The reason I enabled that was I didn't setup a windows VM to test the code changes and I was afraid to break anything on other platform. I guess it makes sense to only build on release branch for now.

**Comment by iwalton3** [comment]
Nope the Mac OS builds still throw Dylib errors. I tried two builds.

 - [One with almost everything from source.](https://github.com/iwalton3/jellyfin-media-player/runs/2324334706?check_suite_focus=true)
 - [One where ffmpeg was additionally told to be static, but didn't actually build static.](https://github.com/iwalton3/jellyfin-media-player/runs/2328271067?check_suite_focus=true)

Both of these runs failed with this error message.

```
Dyld Error Message:
  dyld: Using shared cache: 52762DF1-0E55-3F8B-9588-8169E6D0EB95
Library not loaded: /usr/local/Cellar/ffmpeg/4.3.2_4/lib/libswresample.3.dylib
  Referenced from: /Applications/Jellyfin Media Player.app/Contents/Frameworks/libavcodec.58.dylib
  Reason: image not found
```

**Comment by iwalton3** [comment]
Which if you check the log `libswresample.3.dylib` is bundled, but it insists on using the version in `/usr/local` and not the bundled one.

```
2021-04-12T14:07:22.1136190Z Log:  copied: "/usr/local/opt/ffmpeg/lib/libswresample.3.dylib"
2021-04-12T14:07:22.1139050Z Log:  to "/Users/runner/work/jellyfin-media-player/jellyfin-media-player/build/output/Jellyfin Media Player.app/Contents/Frameworks//libswresample.3.dylib"
```

**Pull request merged**
